name: .NET build

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      appVersion: v0.1
      PostSharpLicense: ${{ secrets.PS_LICENSE }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build .NET for Linux
        run: dotnet build --no-restore -r linux-x64 -c Debug -o ${{ github.workspace }}/output_linux
      - name: Build .NET for Windows
        run: dotnet build --no-restore -r win10-x64 -c Debug -o ${{ github.workspace }}/output_win32
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Create Artifacts for Linux
        uses: actions/upload-artifact@v2
        with:
          name: RMH-linux-${{ env.appVersion}}.${{ env.GITHUB_RUN_NUMBER }}
          path: ${{ github.workspace }}/output_linux/ # or path/to/artifact
          if-no-files-found: error
      - name: Create Artifacts for Windows
        uses: actions/upload-artifact@v2
        with:
          name: RMH-win32-${{ env.appVersion}}.${{ env.GITHUB_RUN_NUMBER }}
          path: ${{ github.workspace }}/output_win32/ # or path/to/artifact
          if-no-files-found: error
      - name: Pack Linux Artifacts
        run: 7z a -tzip ${{ github.workspace }}/RMH-linux-${{ env.appVersion }}.zip ${{ github.workspace }}/output_linux/ -r
      - name: Pack Windows Artifacts
        run: 7z a -tzip ${{ github.workspace }}/RMH-win32-${{ env.appVersion }}.zip ${{ github.workspace }}/output_win32/ -r
