name: .NET Build

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "!*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: windows-latest
            platform: win32
          - os: ubuntu-latest
            platform: linux
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      appVersion: v0.1_${{ matrix.platform }}
      PostSharpLicense: ${{ secrets.PS_LICENSE }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build .NET
        run: dotnet build --no-restore -c Debug -o ${{ github.workspace }}/output
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Create Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RMH-${{ matrix.platform }}-${{ env.appVersion}}.${{ env.GITHUB_RUN_NUMBER }}
          path: ${{ github.workspace }}/output_${{ matrix.platform }}/ # or path/to/artifact
          if-no-files-found: error
      - name: Pack Linux Artifacts
        run: 7z a -tzip ${{ github.workspace }}/RMH-${{ matrix.platform }}-${{ env.appVersion }}.zip ${{ github.workspace }}/output_${{ matrix.platform }}/ -r
